config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :city, :state, :country, :contact_number, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.turbo_stream { render turbo_stream: turbo_stream.append('user_list', partial: 'users/user', locals: { user: @user }) }
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('remote_modal', partial: 'users/form_modal', locals: { user: @user }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace('user_row_' + @user.id.to_s, partial: 'users/user', locals: { user: @user }) }
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('remote_modal', partial: 'users/form_modal', locals: { user: @user }) }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("user_row_#{@user.id}") }
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :city, :state, :country, :contact_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="col-lg-12">
  <h1>Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Profinders</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
        <%= turbo_frame_tag 'remote_modal' %>
      </div>
    </div>  
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div class="modal-body">
    <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, class: "form-label mb-2 mt-3" %>
      <%= form.text_field :name, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group">
      <%= form.label :email, class: "form-label mb-2 mt-3" %>
      <%= form.text_field :email, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group">
      <%= form.label :city, class: "form-label mb-2 mt-3" %>
      <%= form.text_field :city, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group">
      <%= form.label :state, class: "form-label mb-2 mt-3" %>
      <%= form.text_field :state, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group">
      <%= form.label :country, class: "form-label mb-2 mt-3" %>
      <%= form.text_field :country, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group">
      <%= form.label :contact_number, class: "form-label mb-2 mt-3" %>
      <%= form.text_field :contact_number, class: "form-control form-control-lg" %>
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit class: "btn btn-primary", data: {action: "click->bs-modal#submitEnd"} %>
  </div>

<% end %>

app/views/users/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="bs-modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Create New User</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render "form", user: user %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="bs-modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel"><%= modal_title %></h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render partial_name, user: user %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr id="user_row_<%= user.id %>">
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.city %></td>
  <td><%= user.state %></td>
  <td><%= user.country %></td>
  <td><%= user.contact_number %></td>
  <td>
    <%= link_to 'View', user, class: "btn btn-info", "data-controller": "user-modal" %>
    <%= link_to 'Edit', edit_user_path(user), class: "btn btn-success", "data-controller": "user-modal" %>
    <%= link_to 'Delete', user, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this user?' }, class: "btn btn-danger" %>
  </td>
</tr>

app/views/users/_user_detail.html.erb
<div class="modal-body">
  <div class="row">
    <div class="col-lg-12">
      <p class="lead"><strong>Name: </strong> <%= user.name %> </p>
      <p class="lead"><strong>Email: </strong> <%= user.email %> </p>
      <p class="lead"><strong>City: </strong> <%= user.city %> </p>
      <p class="lead"><strong>State: </strong> <%= user.state %> </p>
      <p class="lead"><strong>Country: </strong> <%= user.country %> </p>
      <p class="lead"><strong>Contact Number: </strong> <%= user.contact_number %> </p>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</div>

app/views/users/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "modal", user: @user, modal_title: 'Edit User', partial_name: 'form' %>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<table class="table table-border">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Contact Number</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody id="user_list">
    <% @users.each do |user| %>
      <%= render "user", user: user %>
    <% end %>
  </tbody>
</table>

<%#= link_to "New user", new_user_path(format: :turbo_stream) %>
<%= link_to "New user", new_user_path, "data-controller": "user-modal" %>
<%#= link_to "New user", new_user_path, data: { controler: 'user-modal' } %>

app/views/users/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "modal", user: @user, modal_title: 'Create New User', partial_name: 'form'  %>
<% end %>

app/views/users/show.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "modal", user: @user, modal_title: 'User Details', partial_name: 'user_detail' %>
<% end %>